FROM python:3.9-slim-buster as builder
WORKDIR /tmp
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

FROM python:3.9-slim-buster
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY server /server
ENV PYTHONPATH="${PYTHONPATH}:/server"
ENV PROMETHEUS_MULTIPROC_DIR="/tmp/prometheus"
ENTRYPOINT ["/bin/sh"]